name: helloworld
description: A Flutter app to view PDFs.

publish_to: 'none' # Remove this line if you are planning to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_pdfview: ^2.0.0
  path_provider: ^2.0.11

flutter:
  uses-material-design: true

  assets:
    - assets/chapter1.pdf
    - assets/chapter2.pdf
    - assets/chapter3.pdf
    - assets/chapter4.pdf
    - assets/chapter5.pdf
